### ISSUE TITLE
Searching in the demo is really really slow

### ISSUE THREAD

**Issue by arilotter** [lucaong/minisearch#1]
If I type `bon` in the demo song search, the `n` keydown spends 1.9 seconds in the `searcher` function and freezes the page while this is happening.

I've attached a Chrome profile.
This happens on a Thinkpad X1 Carbon with an i7-8550U (8) @ 4GHz 
[Profile-20190204T125706.json.log](https://github.com/lucaong/minisearch/files/2829221/Profile-20190204T125706.json.log)

**Comment by lucaong** [comment]
Hi @arilotter ,
thanks a lot for reporting this. I cannot seem to reproduce this performance issue on any of my devices or browsers, but I would really be interested in replicating the behavior to investigate it, and therefore I have a few questions for you:

  - What operative system are you using?
  - Does this happen only for the search "bon", or for any search?
  - If I understand correctly, it hangs on the "n", but not on the "o", correct?

Thanks a lot for your help

**Comment by arilotter** [comment]
I'm running NixOS 19, a Linux variant on Kernel 4.20.2. My machine has 16GB of memory.
It's weird about when it hangs:

- "" -> "b" is fine
- "b" -> "bo" is fine
- "bo" -> "bon" is very slow
- "bon" -> "bo" is also very slow (??)

- "" -> "a" is fine
- "a" -> "an" is fine
- "an" -> "ang" is very slow
- "ang" -> "an" is also very slow (??)

**Comment by lucaong** [comment]
Thanks @arilotter 
tomorrow I will test on a Linux machine. The behavior is quite puzzling, and I still could not reproduce it, but I want to get to the bottom of it.

One more question: you mentioned the `searcher` function in your first message. Is it the actual name of a function in the source code, or you mean just the search functionality? I am asking because there is no function called `searcher` in the `MiniSearch` source code or in the demo. Therefore if that's the name of the function that hangs, it might be some other code (maybe a browser extension?).

Thanks again for helping out with this!

**Comment by lucaong** [comment]
Indeed, it seems from the profile you attached, that the `searcher` function that blocks the browser thread is part of the Chrome extension Greentextify:

```json
{"callFrame":{"functionName":"searcher","url":"chrome-extension://hjcfkfbfobmejkjkiecbndbmjhabofbk/greentext.js","scriptId":54,"lineNumber":0,"columnNumber":17},"id":161,"parent":160}
```

I am not sure what is causing the extension to hang, from a quick look at its source it looks like the extension is observing DOM changes, calling a recursive function, and running some regexp when it detects some specific markup. Probably the fast re-rendering due to MiniSearch results and React is causing this recursive function to be invoked very fast on a big DOM tree. If you can confirm that the problem is with the extension, I would close the issue.

Thanks again, also for attaching the profile, which was very useful to pinpoint the issue!

**Comment by arilotter** [comment]
I can confirm the extension causes the issue! Thank you, and I'll be sure to disable extensions before reproducing an issue next time :)
