### ISSUE TITLE
Async search?

### ISSUE THREAD

**Issue by XxPKBxX** [lucaong/minisearch#105]
When I search huge amount of data, it lags. Is there any way to search asynchronously? Or, is there any way to reduce lag while processing huge data?

**Comment by lucaong** [comment]
It is possible to build the index asynchronously, but not to search asynchronously. It is not easy to do that, as search is a CPU bound operation. That said, search should usually be very performant, and scale mostly independently from the number of documents in the index.

Whenever I did observed lags in existing applications using MiniSearch, it was due to code outside of MiniSearch itself, such as rendering the list of results or finding the result among the document list. Of course, it is possible that in your case it is MiniSearch itself that lags, but here are a few anti patterns to avoid:

  - Mapping the search result to document by using something like `results.map((result) => documents.find((doc) => doc.id = result.id))`. This traverses the document list once per each search result, and is not performant. Use `storeFields` or create a map of ID to document instead.
  - Rendering long lists of results efficiently takes special care, even with frameworks like React or similar. If the result list is very long, rendering needs to be optimized with something like `react-window` or other "lazy rendering" technique. This does not depend on MiniSearch, it's just a limitation of the rendering technologies. To debug if this is the problem, try to perform the search but avoid rendering the result list. Is it fast or does it still lag?
  - If you perform fuzzy matching, do not use too large fuzziness values. The defaults are good on most applications, if you customize them, beware that too much fuzziness can make search inefficient, and give you a lot of false positives too. If needed, use normalization or stemming instead (for example if you want "fishing" and "fishes" to match "fish")

Can you share more information about your case?

**Comment by XxPKBxX** [comment]
Yeah, I reindexed whole docs each search. However, it is still lagging when I spam keyboard. Is there any way to fix this? The collection has about 700 items.

**Comment by XxPKBxX** [comment]
I just checked it, and it got fixed. Sorry, and thank you for helping me!

**Comment by lucaong** [comment]
Great that you solved it @XxPKBxX , happy to help!

**Comment by idanadut** [comment]
> I just checked it, and it got fixed. Sorry, and thank you for helping me!

@XxPKBxX @lucaong 
Hi,
How did you solve it?

Generally, works great, but if you spam it with search queries like "jsdnfkjasndfkjasndfkjasndfjksad" it takes really long time to respond and server gets overloaded. The query length is limited but event with 25-30 chars it take long.

**Comment by XxPKBxX** [comment]
I just indexed whole collection when the application is first loaded, and performed search only when input is updated.

**Comment by idanadut** [comment]
Thanks.
I do this as well. But since our collection could contain tens of thousand of object records, and apply fuzzy, it still take very long time.

@lucaong 
 any solution you can share here for your inner code to where exactly to perform some timeout if the operation takes too long?

**Comment by lucaong** [comment]
Hi @idanadut ,
This is strange, longer queries should not be much slower. Are you sure that you are not mistakenly re-indexing upon each search? It’s a common mistake. Refer to my comment above for a list of things to check.

Search should be near instantaneous, even with long or random queries (random queries should be even faster, as they probably don’t match anything). If search is slow, I would take it as an indication that something is off.

Otherwise, if all looks good, one thing you can try is to use a debouncing function on the search, so that it is performed only when the input stops changing.
