### ISSUE TITLE
{ combineWith: 'AND' } performs as exact, not as AND search  

### ISSUE THREAD

**Issue by kal4evskiy** [lucaong/minisearch#11]
hello!
thanks for fixing previous issue.

looks like { combineWith: 'AND' } option performs as exact, not as AND search. and seems like fuzzy option is also ignored in that case

could you pls take a look ? 

thanks

**Comment by lucaong** [comment]
Hi @kal4evskiy ,
thanks for reporting this. I think I need some more information, because I am not sure if I understand the issue.

Can it be reproduced on the [demo application](https://lucaong.github.io/minisearch/examples/)?

If on the demo app I set the advanced options to `Combine terms with: AND` and I select fuzzy search, then search for `beatles madona`, I correctly get `Lady Madonna, The Beatles` as the only result. Am I misunderstanding your issue?

The options should be something like:

```javascript
miniSearch.search('my search query', { combineWith: 'AND',  fuzzy: true })
```

**Comment by kal4evskiy** [comment]
everything works fine with your demo page and with mine test both. 
this time it was a problem with the logic in my config
sorry for the disturb (

and thanks you again for quick support and great lib

**Comment by lucaong** [comment]
No problem, happy that you could figure it out :)
