### ISSUE TITLE
Search return all the documents with the query "something.something"

### ISSUE THREAD

**Issue by daeteck** [lucaong/minisearch#138]
When I search with the term: "something.something" it returns all the indexed documents. 

Let says for example "pepe.c" as query.

  private readonly _miniSearch = new MiniSearch({
    fields: ['fullName', 'email', 'username'],
    idField: 'uuid'
  });

this._miniSearch.addAll([{
  'uuid': 'KRr6ugiUgWCjzEumj0qHR',
  'fullName': 'Lorenzo Lamaz',
  'email': 'lorenzolamaz@gmail.com',
  'username': 'lorenzo'
}, {
  'uuid': 'jzJHja7ln2-PvqSrEwPXo',
  'fullName': 'Federico Lamaz',
  'email': 'federico@yopmail.com',
  'username': 'federicolamaz'
}, {
  'uuid': '_zmrVVp2y1z7CNtLHhSkC',
  'fullName': 'Julieta Lamaz',
  'email': 'julieta@yopmail.com',
  'username': 'julietalamaz'
}, {
  'uuid': '8d0m7eSOzodlNAQEyupIq',
  'fullName': 'Macarena Perez',
  'email': 'macarena@yopmail.com',
  'username': 'macarenaperez'
}, { 'uuid': 'nDmMC4oUtBGeYKLzyPWMc', 'email': 'pepe@pepe.com' }]);

const query = 'pepe.c';

this._miniSearch
    .search(query, { prefix: true, fuzzy: 0.2 })
    .map(result => result.id);

The result is all the documents.

**Comment by rolftimmermans** [comment]
Hey! Thanks for your report. I can help explain why all documents are returned in your example.

To search in documents, all search engines will tokenise the contents. By default, MiniSearch tokenises content by splitting on every occurrence of whitespace or punctuation. An email address like `lorenzolamaz@gmail.com` will be tokenised into `lorenzolamaz`, `gmail`, `com`.

The search query `pepe.c` will be tokenised into `pepe`, `c`. Because you search with `prefix: true` the query for `c` will match `com`, which occurs in all documents in your example.

You will have to ask yourself how search in email addresses should work in your application. I can think of at least two sensible approaches:
* Do you want to search in the username and domain part separately, treating each as a separate token? Then you could tokenise by splitting at `@` only, so that `lorenzolamaz@gmail.com` becomes `lorenzolamaz`, `gmail.com`.
* Or maybe it is actually great to split on all punctuation like it does now? If you have an email address `john.doe@us.sales.example.com`, a query for `john sales` would match it, because the email address was tokenised as `john`, `doe`, `us`, `sales`, `example`, `com`.

This decision is very application-specific, so I can only give some general ideas what you could do to improve the situation. There are probably more options; MiniSearch is very flexible.

### Tokenise on @
If you decide to tokenise on `@`, you should override the `tokenize` function when constructing a MiniSearch instance. Probably only for the `email` field. It could look like this:

```
const defaultTokenize = MiniSearch.getDefault("tokenize")
const miniSearch = new MiniSearch({
  fields: ['fullName', 'email', 'username'],
  idField: 'uuid',
  tokenize: (string, fieldName) => {
    if (fieldName == 'email') return string.split('@')
    return defaultTokenize(string)
  }
})
```

When searching, you probably need to override `tokenize` too. The following would tokenize `example.c` into `example`, `c`, `example.c`. This approach would be helpful if you search within email addresses _and_ regular content. If you _only_ search within email addresses, you might only need `text.split('@')`.

```
miniSearch.search(query, {
  prefix: true,
  fuzzy: 0.2,
  tokenize: text => {
    [...defaultTokenize(text), ...text.split('@')]
  }
})
```

### Treat `com` and other common parts as a stop word

You could keep the default tokenisation, but treat `com` as a stop word. How to deal with stop words is described in the README under [term processing](https://github.com/lucaong/minisearch#term-processing).

This would avoid a search for `c` matching all email addresses ending in `.com`.

### Use prefix search only for longer query terms

I've found that if you type a single letter query term like `c`, it will often match too much.  So it could be sensible to enable prefix search only for longer search terms. In the following example, only 3+ letter terms will be used for prefix search. Maybe that's already enough of an improvement?

```
miniSearch.search(query, {
  prefix: term => term.length > 2,
  fuzzy: 0.2,
})
```

**Comment by daeteck** [comment]
Thank you very much for all the time you spent on this detailed explanation of how the library works internally. 

With this new context I am going to think how to implement the best solution. 

Again, thank you very much.

**Comment by lucaong** [comment]
Nothing to add to the great explanation by @rolftimmermans . I would advise starting with the last suggestion, performing prefix search only on search terms longer than 2 characters: that’s the simplest change and might already meet your requirements.

As a separate note, I will think about adding a paragraph in the documentation about prefix search mentioning that it often makes sense to enforce a minimum prefix length, as  it’s some easy to overlook.
