### ISSUE TITLE
processTerm results in search results being ommited

### ISSUE THREAD

**Issue by anzorb** [lucaong/minisearch#145]
Hi,

I've noticed some strange behavior when using the `processTerm` function, where just by having the function there (and returning the `term`) it omits certain results that were there before. 

```javascript
const data = [
  {
    id: "1",
    name: "Koodo",
    description:
      "Join the Koodo Mobile family for the best phone and data rates. Choose happy with no fixed term contracts required. Get the coolest phones on the tab with affordable smartphone plans. Come in today!"
  },
  {
    id: "2",
    name: "Apple",
    description:
      "Think different. Apple celebrates those who look at life a little differently, providing them with devices that fit their lifestyle and imagination. Stay up-to-date with the latest MacBooks, iPhones, iPads, Apple Watches, and other devices. Visit the Apple Genius Bar for workshops and troubleshooting. All your apple needs are right here."
  }
];

let miniSearch = new MiniSearch({
  fields: ["name", "description"], // fields to index for full-text search
  storeFields: ["name"],
  searchOptions: {
    fuzzy: 0.2
  },
  processTerm: (term, _fieldName) => {
    return term;
  }
});

miniSearch.addAll(data);
console.log(miniSearch.search("iphone").map((r) => r.name));
// prints ["Koodo"]
```

Commenting out the processTerm function prints ["Koodo", "Apple"]. I am not sure I agree with the results, since `iphones` IMO should rank higher than `phones` but that's another issue.

I've tested this with both version 4 and 5.

Here's a codesandbox: https://codesandbox.io/s/minisearch-bug-xqz04n?file=/src/index.ts:1033-1120

Thanks in advance!

**Comment by lucaong** [comment]
Hi @anzorb ,
Thanks for reporting this, I will look into it. Meanwhile, would it be possible for you to try the latest `5.0.0-beta1` to check if the issue occurs there too?

**Comment by lucaong** [comment]
Hi @anzorb , I now understand what is happening, and that is expected behavior. By setting a custom `processTerm`, you are overriding the default one, which normalizes the casing of terms, turning for example `iPhone` into `iphone` to make the search case insensitive. The custom `processTerm` function that you are specifying doesn't apply such normalization, and therefore the search becomes case sensitive, omitting the `Apple` result.

You can see that if you search for `iPhone` instead of `iPhone`, only `Apple` is returned in the results, instead of only `Koodo`.

If you normalize casing in the custom `processTerm`, this is fixed:

```javascript
processTerm: (term, _fieldName) => {
  return term.toLowerCase();
}
```

I will make sure to mention more clearly in the documentation that the default term processor is normalizing case.

**Comment by anzorb** [comment]
Thank you @lucaong! That solved it, and thanks for the awesome lib! Feel free to close.
