### ISSUE TITLE
Support nested list of objects

### ISSUE THREAD

**Issue by springuper** [lucaong/minisearch#154]
In our scenario, we would like to provide full-text search functionality for datasets look like:

```json
{
  "id":"12345",
  "name":"dataset_name",
  "type":"table",
  "columns":[
    {
      "name":"date",
      "type":"int",
      "description":"xxx"
    },
    {
      "name":"container",
      "type":"string",
      "description":"xxx"
    },
    {
      "name":"container_position",
      "type":"int",
      "description":"xxx"
    }
  ]
}
```

when search `container`, we hope it could find out all columns having `container` in its `name` field. Here is an example:

```json
[
  {
    "id":"12345",
    "...": "...",
    "match":{
      "container":[
        "columns[1].name",
        "columns[2].name"
      ],
      "probably there will be better ways"
    }
  }
]
```

Looks like currently there is no good way to support this feature. Any thoughts?

**Comment by lucaong** [comment]
Hi @springuper ,
it is possible to index nested lists of objects by specifying a custom `extractField` function, like [shown here](https://github.com/lucaong/minisearch#field-extraction). In your example, it could work like this (assuming here that the columns are always 3):

```javascript
let miniSearch = new MiniSearch({
  fields: ['name', 'type', 'columns.0.name', 'columns.1.name', 'columns.2.name'],
  extractField: (document, fieldName) => {
    // Access nested fields
    return fieldName.split('.').reduce((doc, key) => {
      const intKey = parseInt(key, 10)
      return doc && doc[isNaN(intKey) ? key : intKey]
    }, document)
  }
})

miniSearch.addAll(documents)

miniSearch.search('container')
// => [{ id: '12345', ...: ..., terms: ['container'], match: { container: ['columns.1.name', 'columns.2.name'] }}]
```

Alternatively, depending on what's more appropriate for your use case, you could consider each column as a separate document.

**Comment by springuper** [comment]
very appreciated for your quick reply. yeah, it should work. the only one issue is that the count of items in `columns` field is not fixed, it might be 1-1000. I hope there could be a better way to handle it.

**Comment by lucaong** [comment]
Here’s an example of what I meant:

```javascript
let miniSearch = new MiniSearch({
  fields: ['name', 'type', 'columnNames'],
  extractField: (doc, fieldName) => {
    if (fieldName === 'columnNames') {
      return doc.columns.map((column) => column.name).join(' ')
    } else {
      return doc[fieldName]
    }
  }
})

miniSearch.addAll(documents)

miniSearch.search('container')
// => [{ id: '12345', ...: ..., match: { container: ['columnNames'] }}]
```

This solution adapts to any number of columns per document, but on the other hand the match data does not provide info on which specific column matches the search.

**Comment by springuper** [comment]
I got your points, these ways should be workable, will try them first. Thank you so much! I'll close this issue first.

BTW, looks like there is no option similar to `findAllMatches` option in [Fuse.js](https://fusejs.io/api/options.html#findallmatches), any particular reason on that?

**Comment by lucaong** [comment]
Hi @springuper ,
happy to see my suggestions helped.

Regarding `findAllMatches` in Fuze, to understand your case, what do you need exactly?

`MiniSearch` doesn’t have such flag because, differently from Fuze, it relies on an index. This means that `MiniSearch` is generally more performant to retrieve results, and can afford retrieving all matches all the time (like `findAllMatches: true` in Fuze), and use the information to compute the score. If a term matches twice, the result will be more relevant (all else being equal). 

On the other hand, `MiniSearch` does not indicate in the results the position of the matches. That’s because that would require storing term offsets in the index, making it substantially larger, and therefore going against the project goals.

Fuze traverses the whole collection upon each search, without relying on an index. This on one hand makes Fuze generally less efficient than `MiniSearch`, on the other it allows reporting the position of each match.

In principle, if you need the position of matches to highlight them, the best way to do so in `MiniSearch` is to first retrieve the search results, then use the `match` information to scan the matching documents and highlight the matches. If I find the time, I could post an example later.

**Comment by lucaong** [comment]
A quick and dirty example of what I meant in my previous comment is this function, that given a matched term and the text of the field that matched it, returns the offsets at which the term is found. The matched terms and the name of the fields in which they are found are in the `match` attribute in `MiniSearch` results.

```javascript
const getMatchOffsets = (term, field) => {
  const termRegexp = term.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
  const matches = [...field.matchAll(new RegExp(termRegexp, 'gi'))]
  return matches.map((match) => [match.index, match.index + term.length])
}

getMatchOffsets('foo', 'the foo in the Foo bar')
// => [ [4, 7], [15, 18] ]
```

Such a function could be used on the results of a search to help highlighting matches, if that is what your goal is.

**Comment by springuper** [comment]
thank you so much, @lucaong , it works for me!
