### ISSUE TITLE
bug: setting idField does not work

### ISSUE THREAD

**Issue by samuelstroschein** [lucaong/minisearch#156]
Setting the idField does not seem to work.

### Running the following code:

Run the example yourself https://stackblitz.com/edit/node-x225pp?file=index.js

```ts
// run `node index.js` in the terminal

import MiniSearch from 'minisearch';

const respositories = [
  {
    name: 'inlang/inlang',
    iconSrc: 'https://github.com/inlang.png',
    description: 'Open Source Localization Solution for Software.',
    stars: 0,
    url: '',
  },
];

const minisearch = new MiniSearch({
  idField: 'name',
  fields: ['name', 'description'],
});

minisearch.add(respositories);

console.log(minisearch.search('in'));

```

### yields the following error message:
`Error: MiniSearch: document does not have ID field "name"`

**Comment by lucaong** [comment]
Hi @samuelstroschein ,
the issue in your code is that you are calling `add` instead of `addAll`:

```javascript
// minisearch.add expects a single document, but a collection is passed here.
// Since there is no `name` field in the collection itself, this raises the error
// `Error: MiniSearch: document does not have ID field "name"`
minisearch.add(respositories);

// Instead, when indexing a whole collection, use minisearch.addAll
minisearch.addAll(respositories)
```

The example you linked has the same issue, but also uses the `url` field as an ID, but such field is empty, so you might run into the same error even after switching to `addAll`.

Unrelated, but anticipating another possible issue, you are searching for `"in"`, but you are not using prefix search, so even after fixing the issue you will get no results. If you want to also find documents that contain terms starting with `"in"`, such as `"inlang"`, you can do `minisearch.search('in', { prefix: true })`.

I hope this helps :)
