### ISSUE TITLE
Phrase Search?

### ISSUE THREAD

**Issue by jfinger** [lucaong/minisearch#159]
Hi. I am a Github newbie. Please forgive any unintentional faux pas.

Thank you for a wonderful library!

I would like to be able to search for particular phrases. More specifically,

- I created an 2M index for a large-ish book to be made available on the Web. 
- There are O(70) chapters in the book, each one a document entry in the index.
- There is really only one web page, which I'll call `w.html`. Each chapter's content simply replaces the content of `<div id="ChapterContent">` in `w.html` when the user navigates to that chapter via the UI in `w.html`.
- What I really want is control-F generalized to go through all the chapters in the book. For example, I'd like to be able to search for "Firstname Lastname" combinations, among others. The fact that FirstName and Lastname both appear on the page is not a match, in and of itself.

It appears that the best bet is to use combineWith: "AND", and then post-process the results, similarly to what is proposed in [#37 Highlighting Matches](https://github.com/lucaong/minisearch/issues/37).

The approach would be to filter matched documents, searching for the desired phrase in the index. If there are matches to the phrase, I could then highlight the matches as in #37 and provide UI similar to control-F for going through all the chapters in the book.

Is there an easier or better way?
Many thanks.

**Comment by lucaong** [comment]
Hi @jfinger , thanks for your kind words!

> It appears that the best bet is to use combineWith: "AND", and then post-process the results, similarly to what is proposed in https://github.com/lucaong/minisearch/issues/37.

That's essentially correct. `MiniSearch` uses a "bag of words" approach: it does not take into account where the terms appear in a document, or if they appear next to each other. This is a trade-off by design: it would certainly be good to consider term position and proximity in the scoring of results, but in order to do so `MiniSearch` would have to save in the index also the position in which each term is located in each document. This would make the index much larger, and be incompatible with the [project goals](https://github.com/lucaong/minisearch/blob/master/DESIGN_DOCUMENT.md#goals-and-non-goals). Unfortunately, this prevents `MiniSearch` from supporting phrase match out of the box.

As you correctly note, it is a very similar issue as https://github.com/lucaong/minisearch/issues/37, and what you propose looks like the best solution: use `MiniSearch` to find candidate results, then filter only those where the phrase is actually present. I unfortunately do not have a better way to recommend you.

**Comment by jfinger** [comment]
Thanks, Luca. And thank you for the quick response.

**Comment by lucaong** [comment]
Welcome :)
