### ISSUE TITLE
What is the best approach to filter the dates?

### ISSUE THREAD

**Issue by AndrzejNowakKBA** [lucaong/minisearch#173]
Is there a good way of searching the documents only by date? Let's say we have a documents with filed creationDate. They contains the date in following "08/08/2022" format. How to set the options for searching documents only from 08/2022 and also be able to get 08/08 only instead of 08/10 or 20/08?

**Comment by lucaong** [comment]
Hi @AndrzejNowakKBA ,
the best approach is to add `creationDate` to the `storeFields` option, and use the `filter` option to filter. Something like:

```javascript
const documents = [
  { id: 1, title: 'California Sun', creationDate: '07/02/1961' },
  { id: 2, title: 'Paperback Writer', creationDate: '23/05/1966' },
  { id: 3, title: 'Going to California', creationDate: '07/08/1969' }
]

const miniSearch = new MiniSearch({
  fields: ['title'],
  storeFields: ['creationDate']
})

// Search for "California" only in year 1969
miniSearch.search('california', {
  filter: ({ creationDate }) => creationDate.endsWith('1969')
})

// Search for "California" only in 02/1961
miniSearch.search('california', {
  filter: ({ creationDate }) => creationDate.endsWith('02/1961')
})
```

This approach is the best when mixing a full-text search with filtering by date. If you instead wanted to _only_ filter by date, without a full-text search, one option would be to index the different parts of `creationDate`:

```javascript
const miniSearch = new MiniSearch({
  fields: ['title', 'creationDay', 'creationMonth', 'creationYear'],
  extractField: (doc, fieldName) => {
    if (fieldName === 'creationDay') {
      return doc.creationDate.split('/')[0]
    } else if (fieldName === 'creationMonth') {
      return doc.creationDate.split('/')[1]
    } else if (fieldName === 'creationYear') {
      return doc.creationDate.split('/')[2]
    } else {
      doc[fieldName]
    }
  }
})

// Search for all documents with creation year 1969
miniSearch.search('1969', { fields: ['creationYear'] })

// Search for all documents created in 08/1969
miniSearch.search({
  queries: [
    { queries: '1969', fields: ['creationYear'] },
    { queries: '08', fields: ['creationMonth'] }
  ],
  combineWith: 'AND'
})
```

Note though that for this last use case where you do not perform full-text search, as the requirements grow, you might hit a limit where it's just easier to create yourself a mapping sorted by `creationDate` and some range search logic, rather than relying on `MiniSearch` (which is designed for full-text search after all, and can help in this case, but might or might not be the best tool).

I hope this helps :)

**Comment by AndrzejNowakKBA** [comment]
Thank You. Your answer helped me a lot :)
