### ISSUE TITLE
Possible to include a list of synonyms for term matching?

### ISSUE THREAD

**Issue by saigelosli** [lucaong/minisearch#177]
Hopefully the title is clear. I wonder if it is possible to supply a list of synonyms to allow matching even if the specific search term is not present in the indexed document. Such as:

automobile: "auto", "car", "sedan", "coupe"

**Comment by lucaong** [comment]
Hi @saigelosli ,
yes, this is a common need :) there are basically two main ways to do that:

One way is to add to your documents a new field, containing the synonyms or alternative spellings. Let's call it `additionalTerms` for this example. This field would be indexed and searchable, but not visible to the user, so that searching for `auto` would return all results that contain that term either in the "standard" fields, or in the `additionalTerms` field. This approach is more appropriate when you can manually decide which `additionalTerms` to use for each document.

The other way is to use the `processTerm` option to expand terms adding their synonyms too. Here is how it would work:

```javascript
const synonyms = {
  car: ["car", "automobile", "auto", "sedan", "coupe"],
  # ...more synonyms
}

const documents = [
  { id: 1, text: "A very nice automobile" },
  /* ...more documents */
]

const miniSearch = new MiniSearch({
  fields: ['text'],
  searchOptions: {
    /* At search time, expand each term to all its synonyms, if any */
    processTerm: (term) => synonyms[term] || term
  }
})

miniSearch.addAll(documents)

miniSearch.search("car")
// => [{ id: 1, ... }]
```

Now, a search for `"car"` is expanded to all its synonyms. Note that this has also some effects on the ranking of results, as the effective search query is different (so, for example, documents containing both `"car"` and `"auto"` will score higher than those containing only `"car"`. Also, note that this strategy would not work if using the `combineWith: 'AND'` option.

**Comment by lucaong** [comment]
That’s great to hear! 🙂
