### ISSUE TITLE
Does heavy indexing activity block ability to search?

### ISSUE THREAD

**Issue by reubenfirmin** [lucaong/minisearch#217]
I have an issue in my application where search stops working intermittently while heavy indexing activity is happening. It seems to be happening within MiniSearch, but I'm not yet 100% on it. Does it sound possible? I saw references to "blocking the main thread" in the API docs, so I'm wondering if that's happening. Is there a workaround so that search is kept alive no matter what?

**Comment by reubenfirmin** [comment]
I'm leaning towards the index being corrupted. I will try a vacuum when this next happens to see if it fixes it.

**Comment by lucaong** [comment]
Hi @reubenfirmin ,
It is possible that heavy indexing block the main thread. If that’s the case, try using `addAllAsync` instead of `addAll`: indexing will slow down, but it will leave space for other operations such as search.

That said, without knowledge of your case it’s hard to say if indexing is the problem. Consider that in many cases I have seen, what can easily block search is not so much indexing, but rather rendering long lists of results. If that’s the case, one solution is to render the list lazily upon scroll (either like “infinite scrolling”, or using something akin to `react-window`)

**Comment by reubenfirmin** [comment]
@lucaong Thanks for the answer - I ruled this out. It's actually chrome shutting down my extension after some inactivity that causes this. I'm working on a fix.
