### ISSUE TITLE
Is it possible to make autoSuggest suggest the entire title of my blogs instead of just one word?

### ISSUE THREAD

**Issue by wentallout** [lucaong/minisearch#231]
I never use a library like this before so sorry for my limited knowledge.

**Comment by lucaong** [comment]
Hi @wentallout ,
with the `autoSuggest` method, it is NOT possible to autocomplete the full title of the blog post. That's because `autoSuggest` will only auto-complete one word. The trade off is that `autoSuggest` works out of the box, with no setup, but on the other hand it can only work on a term level, not on a field level. Whenever one has a specific autocomplete need not covered by `autoSuggest` out of the box, it's often better to implement some custom logic using the `search` method.

In particular, it is possible to implement what you need by performing a prefix search, restricted to the `title` field, and show the title of the best matching articles in the tooltip.

**Comment by lucaong** [comment]
@wentallout I hope this answer helps you. Since I think this solves your issue, and there is no further reply, I will go on and close the issue for now, but feel free to reply if more information is needed.
