### ISSUE TITLE
can i use it with a cordova app?

### ISSUE THREAD

**Issue by Tazkerah** [lucaong/minisearch#24]
i have a cordova app, a drug reference with about 200 html pages (total size of them is about 40mb), is there a way that i can use minisearch to search the whole app (the whole static site) off-line? and if yes can you illustrate how

**Comment by lucaong** [comment]
Hi @Tazkerah ,
yes, it is possible to use `MiniSearch` in a Cordova app. Just use it in the same way you would in a standard JavaScript app.

In your case, the main problem is that `MiniSearch` cannot directly parse the HTML pages. The best solution is to produce a JSON (or JavaScript) version of the data to be indexed (the drug information) and feed it to `MiniSearch`.

For example, if you wanted to search by name, you could create a JSON file like:

```json
[
  {
    "id": 123,
    "name": "Aspirin"
  },
  {
    "id": 321,
    "name": "Paracetamol"
  }
]
```

Then, in the app, you would retrieve the file and index it:

```javascript
const json = getJsonFile() // How you retrieve the JSON file is up to you
const drugs = JSON.parse(json)

const miniSearch = new MiniSearch({ fields: ['name'] })

// Index all drug data
miniSearch.addAll(drugs)
```

**Comment by Tazkerah** [comment]
first of all thank you for replaying. 
well, the truth is I'm not really a programmer, so if you would be so kind to make through these things:
1. how should i convert the data into json and feed them to miniSearch 
2. how to include miniSearch in the cordova project
3. does miniSearch has any level of support t Arabic language

if you want to have a look to the app https://play.google.com/store/apps/details?id=com.tazkerah.tazkerahrx&hl=en_US

or i can send you the the project if that would help

best regards

**Comment by lucaong** [comment]
Hi @Tazkerah ,
sorry, I won't be able to help you with the details (`MiniSearch` is one of my open-source projects, which I maintain for free, aside of my full-time job), but here's some basic ideas:

  1. [JSON](https://en.wikipedia.org/wiki/JSON) is a data serialization format. Depending on how big your data is, you could create the JSON file manually (e.g. by copy/pasting textual information) or you might write a script that does it for you. In your case you probably should create a JSON array where each element is one drug, with a unique `"id"` field and the other fields you want to search among.

  2. Cordova apps are standard JavaScript applications, so the instructions on how to install `MiniSearch` apply to Cordova too. That said, packaging JavaScript applications is unfortunately not exactly simple. The simplest option is to download a built version of MiniSearch (for example version `2.1.1` [here](https://cdn.jsdelivr.net/npm/minisearch@2.1.1/dist/minisearch.min.js)), and to include it in your app by adding a `<script>` tag in your HTML pages. A more modern option, but also more complex, is to install `MiniSearch` with `npm` or `yarn`, `import` it in your project, and use a JavaScript bundler like [webpack](https://webpack.js.org) or [parcel](https://parceljs.org) to package your whole JavaScript application. In any case, none of this is specific to `MiniSearch`: you can install and use `MiniSearch` in the same way as other JavaScript packages.

  3. Yes, `MiniSearch` should support non-latin scripts, including Arabic. To be honest I never tested specifically with Arabic language, but other non-latin scripts like Cyrillic were tested by other users, and I don't anticipate any issue there. One caveat might be that prefix search might not work as expected with right-to-left scripts, but I think it should be fixable by using a custom tokenizer that reverses the character order upon indexing.

I hope this points you in the right direction.

**Comment by Tazkerah** [comment]
THANK YOU!

**Comment by Tazkerah** [comment]
Buonasera
i've converted the data to json format, but when i try to get the data from json file i get CORS error, as there is no server in the app, or maybe i am missing something.
i really thought i could do it but as you know "Tra il dire e il fare c'é di mezzo il mare", 
puoi guardare un attimo questo, per favore?
https://drive.google.com/open?id=1GjxxOgWcbcVF4oZHnhwIVoQvK_McM1hg
grazie

**Comment by lucaong** [comment]
Hi @Tazkerah ,
please consider that unfortunately this is not an issue with MiniSearch, so I cannot invest my time in investigating it: I hope you understand that while I would like to help, I cannot really debug you app.

That said, here are a few points that might help you:

  - If you host your `json` remotely, you will have to whitelist the origin with the [Cordova whitelist plugin](https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-whitelist/#network-request-whitelist). Here is [another useful explanation](https://docs.microsoft.com/en-us/visualstudio/cross-platform/tools-for-cordova/security/whitelists?view=toolsforcordova-2017) of the whitelist plugin.

  - If you host your `json` locally, you should be able to request it with something like the following (just an example, you will have to figure out the details for your specific app):

```javascript
fetch('json/my-file.json')
  .then((response) => response.json())
  .then((data) => {
    // do something with data, like index it with miniSearch.addAll(data)
  })
```

  - Alternatively, if your data is static and you want to avoid fetching it, you could store it as a JavaScript file that creates a global variable instead of a JSON file, and load it in your `index.html` with a script tag:

```javascript
// js/drugs.js file declaring a global variable that contains all the drug data
var drugs = [
  {
    "id": 123,
    "name": "Aspirin"
  },
  {
    "id": 321,
    "name": "Paracetamol"
  },
  // ...and more
]
```

```html
<head>
  <script src="js/drugs.js"></script>
  <script src="js/minisearch.min.js"></script> 
  <script src="js/myscript.js"></script> 
</head>
```

In `myscript.js` you will then use the global variable, like: `miniSearch.addAll(drugs)`. The script tag for `js/drugs.js` has to come before the one for `js/myscript.js`, because the variable has to be defined before it can be used.
