### ISSUE TITLE
Should documents with fields that start with the search term score higher?

### ISSUE THREAD

**Issue by ItaiYosephi** [lucaong/minisearch#275]
Hi, in the following screenshot taken from the demo, I search for the word love.
I would expect that the results the came sixth, would be first. it both start with search term, an is exact match.
Is there a way to configure minisearch to do that?
![CleanShot 2024-07-22 at 09 34 33](https://github.com/user-attachments/assets/9777f423-7276-4b6b-aee3-ecd32ea48b72)

**Comment by lucaong** [comment]
Hi @ItaiYosephi ,
when searching on a single field, with default options, the behavior you describe is already what MiniSearch does. Here is an example, using only exact match (no fuzzy nor prefix search) and searching only the title field:

<img width="911" alt="Screenshot 2024-07-22 at 10 17 06 AM" src="https://github.com/user-attachments/assets/0f2ab0ad-27b4-4e88-8f07-d9f83de7463b">

As you can see, the songs with a title containing just the term "Love" are ranking first.

In your screenshot the song titled just "Love" is not the first result is because, due to prefix search, some results match less common terms like "Lovergame" or "Loversong", and "I Never **Loved** A Man The Way I **Love** You" matches twice. Less common terms are considered more specific and therefore get a higher score in most scoring algorithms like BM25+ (used by MiniSearch) and Tf-Idf.

Note that the position of the matched term in the text (whether it's at the beginning of the sentence or not) has no influence on the scoring though, because MiniSearch by design uses a "bag of words" approach that does not consider the order of terms. This enables MiniSearch to keep a much smaller index, which fits in the process memory. If needed, one could use the `boostDocument` option to boost results where tone of the query terms is at the beginning.

I hope this helps!

**Comment by ItaiYosephi** [comment]
@lucaong thank you for your through response!
