### ISSUE TITLE
Remove conjunction, adverbs and punctuations from search Input

### ISSUE THREAD

**Issue by sharmaViks** [lucaong/minisearch#276]
If I have a searchInput as "samsung and apple" and I am searching on data with fields ['name,'description'].

data = [
{
name:'Samsung',
description:'best phone in the world'
},
{
name:'Iphone',
description:'best apple phone in the world'
},
{
name:'Microsoft',
description:'best app and company'
}]

Then miniSearch is giving me Micorsoft as well because description contains the keyword 'and' . How can we skip the  conjunction, adverbs and punctuations.

**Comment by lucaong** [comment]
Hi @sharmaViks ,
with larger real-world collections of documents, the BM25+ ranking algorithm implemented by MiniSearch will usually deal with this issue by itself.

In your example, the problem is mostly due to the fact that there are only four documents, and only one of them contains the term `and`. Therefore, the ranking algorithm considers `and` a quite specific term: in your example, `and` is no more common than `samsung` or `apple`. With more documents, BM25+ will automatically discount the relative importance of terms like conjunctions that occur in many documents, and that therefore do not discriminate well between results.

That said, if you want to remove a specific list of "stop words" from documents, you can use the `processTerm` option:

```javascript
let stopWords = new Set(['and', 'or', 'to', 'in', 'a', 'the', /* ...and more */ ])

// Perform custom term processing (here discarding stop words and normalizing case)
let miniSearch = new MiniSearch({
  fields: ['title', 'text'],
  processTerm: (term, _fieldName) =>
    stopWords.has(term) ? null : term.toLowerCase()
})
```

I hope this helps :)
