### ISSUE TITLE
Search doesn't include dashes.

### ISSUE THREAD

**Issue by thehypergraph** [lucaong/minisearch#277]
So I noticed recently that minisearch@7.1.0, at least as I have configured it, doesn't recognize dashes in a string, Here is the code:

```
const minisearch = new MiniSearch({
    fields: ['caseName', 'clientName', 'jobNumber'],
    storeFields: ['id'],
    searchOptions: {
      prefix: true,
    },
  })

  minisearch.addAll(cases)

  const results = minisearch.search(terms)
```

So if I have a field with a value of alpha-beta, and another with alpha-kappa, then alpha will match both records, beta matches alpha-beta, and kappa matches alpha-kappa, but alpha-b still matches both, I assume because prefix search is on.

Is there a way around this, while still enabling prefix search? 

Thanks.

**Comment by lucaong** [comment]
@thehypergraph that's correct: by default, MiniSearch splits terms by Unicode space or punctuation, and dashes are considered punctuation.

The RegExp currently used by the tokenizer is `/[\n\r\p{Z}\p{P}]+/u`, where `\p{Z}` are all Unicode spaces and `\p{P}` are all Unicode punctuation characters (including `-`).

This can be changed by specifying a custom tokenizer. For example, instead of the whole punctuation class `\p{P}`, one could specify each individual punctuation character class (`\p{Pi}\p{Ps}\p{Pc}\p{Po}`) and exclude dashes (`\p{Pd}`):

```javascript
let miniSearch = new MiniSearch({
  fields: ['caseName', 'clientName', 'jobNumber'],
  tokenize: (string, _fieldName) => string.split(/[\n\r\p{Z}\p{Pi}\p{Ps}\p{Pc}\p{Po}]+/u),
  searchOptions: {
    prefix: true,
  },
})
```

I hope this helps.

**Comment by thehypergraph** [comment]
Thanks, that helped!
