### ISSUE TITLE
Why does the generic passed to the MiniSearch constructor not affect the typing of the SearchResult?

### ISSUE THREAD

**Issue by xanera** [lucaong/minisearch#279]
<img width="713" alt="image" src="https://github.com/user-attachments/assets/4f506d18-597f-4ae1-b563-897a700e42b6">
<img width="633" alt="image" src="https://github.com/user-attachments/assets/e21cae32-6d31-4c0c-9abd-d426afca7555">

**Comment by lucaong** [comment]
Hi @xanera,
that's because MiniSearch started as a JavaScript project, and even nowadays a large part of its users (majority?) uses it in JavaScript. The document type is not directly connected to the result type, the `extractField` option in particular can in principle perform any transformation from the source document to the stored fields returned in the result, making it impossible to make the result stricter in type without a large breaking change. I would like to introduce better typing in the future, but I intend to do that in a way that does not impose a large breaking change to the many existing JavaScript project using it, which would not benefit from stricter types.

If you are interested, similar discussions also happened in #208, #229, and #257 . I have a proposal in mind that would address this issue without a huge breaking change, I will try to outline it in the near future.
