### ISSUE TITLE
Support string array as documents

### ISSUE THREAD

**Issue by bitofbreeze** [lucaong/minisearch#280]
Fuse supports this https://www.fusejs.io/examples.html#search-string-array
fuzzysort does too https://github.com/farzher/fuzzysort#options

Would be nice, especially when trying to conserve memory.

**Comment by bitofbreeze** [comment]
Thanks, I was able to get this working:

```
const documents = ['test', 'test2'];

const miniSearch = new MiniSearch({
  fields: [''],
  extractField: (document, fieldName) => {
    return document;
  }
});

miniSearch.addAll(documents);

let results = miniSearch.search('test');
```

It seems a little hacky since we are a putting an empty string for the field since otherwise no field is registered, but it works so this isn't technically an issue. Thanks again.

**Comment by lucaong** [comment]
Ah, I had misunderstood your case: I thought you wanted to index documents having a field which is an array of strings, like `tags` in the example above. Instead, I now see you meant that each document is simply a string.

Since `MiniSearch` needs IDs, you can simply map the string array to objects:

```javascript
const strings = [
  'something interesting',
  'something else entirely',
  'anything else'
]

const documents = strings.map((str, idx) => ({ id: idx, text: str }))

const miniSearch = new MiniSearch({
  fields: ['text'],
  storeFields: ['text']
})

miniSearch.addAll(documents)

miniSearch.search('something')
// => [
//  { id: 0, text: 'something interesting', score: ... },
//  { id: 1, text: 'something else entirely', score: ... }
// ]
```

Note that the original strings won't be copied in the document objects, only referenced. If you don't reference the `documents` array after indexing, it will also be garbage collected.
