### ISSUE TITLE
Irrational behaviour in the demo app?

### ISSUE THREAD

**Issue by hankolsen** [lucaong/minisearch#3]
Hi!

Thank you for an interesting project! I found it via the Codrops mailing list.
I was trying out some searches in the [demo application](https://lucaong.github.io/minisearch/examples/) and noticed something that I find odd.

If you start typing '**eve**' you get a list of potential matches including '**eve**', '**everlast**', and '**everclear**'.
If I add an '**r**' to the search so the search term in '**ever**', then 'everlast' and 'everclear' disappears and the list is replaced with 'ever never'.
Shouldn't the search term 'ever' still match 'everlast' and 'everclear'?

**Comment by lucaong** [comment]
Hi @hankolsen ,
that is a very reasonable point. The issue is that auto suggestions can be a bit surprising. Here is an explanation of why suggestion currently behave like that, and my proposal about how to make it more intuitive.

Auto suggestions are sorted by decreasing relevance of the results that would be returned by the suggested search (as calculated by Tf-Idf). Furthermore, the demo truncates the suggestion list when the relevance score is less than half of the first suggestion. Suggestions that are closer to the partial query are weighted more (i.e. if typing `hel`, assuming equally relevant results, `help` is suggested before `hello`. If `hello` gives more relevant results though, it might still be suggested before).

When typing `eve`, the suggested queries that lead to the most relevant results are `eve`, `everlast` and `everclear`. There might be more suggestions, that are rejected because they are less than half as relevant as `eve`. When typing `ever`, the suggestion `ever never` matches strongly, because both `never` and `ever` match `ever` very closely, and appear together in some document which is therefore very relevant. The suggestions `everlast` and `everclear` are also returned by `MiniSearch`, but the demo rejects them because their computed relevance is less than half the one of `ever never`.

A less stringent truncation criteria in the demo would keep `everlast` and `everclear` among the suggestions, and lead to more intuitive results. I will add this improvement to the demo, as you are right that it is confusing now.

Thanks for reporting this!

**Comment by hankolsen** [comment]
Thanks for a prompt reply and a thorough walkthrough of the logic behind!

**Comment by lucaong** [comment]
I updated the demo with a slightly better logic around suggestions. Admittedly, auto suggestions can still be a bit unintuitive, and are definitely a feature that is open to future improvements. That is also the reason why I am not yet specifying its intended behavior strictly in the API documentation.
