### ISSUE TITLE
How to limit the number of results

### ISSUE THREAD

**Issue by dzapata14** [lucaong/minisearch#35]
Hi Luca,

Excellent tool, I am testing and it works great so I would ask how to limit the number of results that returns, for example I only want the first 10 results of one search.

I really appreciate the help.

Regards from Ecuador

**Comment by lucaong** [comment]
Hi @dzapata14 ,
you can limit the results to the top N with the [JavaScript Array `slice` method](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/slice):

```javascript
# If we want the top 10 results:
miniSearch.search('something').slice(0, 10)

# If we want the top 3 results:
miniSearch.search('something').slice(0, 3)
```

There is no special option in MiniSearch to limit results, because MiniSearch anyway has to compute all results and then sort them by relevance score. Therefore, limiting the results internally would not be faster than using the standard `slice` method on the result array.
