### ISSUE TITLE
Expose default tokenizer and term post-processor

### ISSUE THREAD

**Issue by Alxandr** [lucaong/minisearch#6]
I've written code to compose different tokenizers and term post-processors together, however, I would like to be able to fall back to the built-in ones. Today, I do this by copying the regex/logic into my application, however it would be much better if they were available as exports from the minisearch package so that they can be built uppon.

**Comment by lucaong** [comment]
Good point, I will add this in the next release. It's specifically important for the `tokenize` and `processTerm` options, but it would be better to have a generic way to get default options.

My initial idea would be to expose the default options as a static method:

```javascript
MiniSearch.getDefault('tokenize') // => default tokenize function
```

The reason for this syntax, compared with a property accessor (e.g. `MiniSearch.tokenize`), would be to prevent changing the defaults with an assignment, which could easily lead to troubles.

**Comment by Alxandr** [comment]
`Object.freeze(defaultOptions)`?

**Comment by lucaong** [comment]
I was thinking the same, but opted for a static method instead, because assigning on non-configurable properties is silently failing:

```javascript
MiniSearch.defaultOptions = { something: 'else' } // no error, but defaultOptions won't be changed
```

So it achieves the goal of not allowing to change the defaults, but might be surprising for users who think they did.

I released `v.1.1.2` with the new `getDefault` static method, which also throws an error for unknown options, saving from possible typos. I hope this works well for your use case.

Thanks again for your help reporting this!
