### ISSUE TITLE
Usage with Redux

### ISSUE THREAD

**Issue by smebberson** [lucaong/minisearch#64]
Is there a way to use this with Redux?

I have a couple of React components creating their own minisearch stores using the same data from Redux. I'd rather put the minisearch store into Redux and have one instance of that data rather than two.

It's better to store plain objects in Redux and I'm wondering is there a way to retrieve the underlying data structure for a minisearch store, store it in Redux, and then 'rehydrate' into minisearch again to actually search the data?

**Comment by lucaong** [comment]
Hi @smebberson ,
For this purpose, I personally usually store a MiniSearch instance in the context, or somewhere else than Redux. But that said, it's also possible to do what you describe by leveraging on an existing feature. Here's how:

```javascript
// Original minisearch istance:
let miniSearch = new MiniSearch({ /* ...some options */ })

// Get a plain object representation of the index:
const serializedIndex = miniSearch.toJSON()

// Re-hydrate it in another scope:
miniSearch = MiniSearch.loadJS(serializedIndex, { \* these options should be the same that were originally used *\ })
```

A few notes and caveats, that hopefully explain why it's usually more convenient store the MiniSearch instance rather than the "plain object":

  - `miniSearch.toJSON()` does NOT return a JSON string, but rather a plain object representation of the index. If you think the method name is confusing, so do I 🙂 , but this is in the [JS specifications of how objects get serialized by `JSON.stringify()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#Description)

  - Differently from its "cousin" `MiniSearch.loadJSON()`, `MiniSearch.loadJS()` is not documented, and therefore to be considered private API: it works, and is tested, but is part of an API that I am still want to reserve the chance to experiment with before declaring it public. That's because the serialization format of the index has a few trade-offs: currently, it's optimized for speed, but it's tightly bound to the specifics of the index data structure. You can definitely use it, but it _could_ change in newer versions of MiniSearch (even though it is unlikely to change in a minor version).

  - You need to pass to `MiniSearch.loadJS()` the same options that you used in the constructor of the original instance. That's because some options are functions, and cannot be serialized as part of the index.

For other cases when one needs to serialize the index, you could also use the public [serialization API](https://lucaong.github.io/minisearch/MiniSearch.html#.loadJSON) with `JSON.stringify(miniSearch)` and `MiniSearch.loadJSON()`, but in your case you would waste resources in serializing/deserializing JSON instead of working with plain objects in the way described above.

In sum, what you described is possible, but I usually suggest solve that problem differently.

I hope this helps!

**Comment by lucaong** [comment]
I'll close the issue, as I think the answer should solve it, but please comment on it if not.

**Comment by smebberson** [comment]
Thanks for your response. That’s great to know and I’ll definitely be putting it to the test!!
