### ISSUE TITLE
Partial matching inside words?

### ISSUE THREAD

**Issue by Uninen** [lucaong/minisearch#67]
First, Thank You for minisearch, it's a great tool! 👍 

My question: is there a way to include results that would find an item containing the word `Raymond` with search `mon` (Ie. the same kind of results that `String.prototype.includes()` yields)?

**Comment by lucaong** [comment]
Hi @Uninen , thanks for the kind words!
As to your question, no, unfortunately, MiniSearch won't match inside words (apart from cases that can be solved with fuzzy matching, like "aymon" for "Raymond"). If the match was at the beginning of the word, you could use prefix search, but otherwise I am afraid MiniSearch is not the right tool for this case.

**Comment by Uninen** [comment]
Ok, thanks for your reply 👍

**Comment by lucaong** [comment]
Welcome 🙂 it might help to add that [lunr.js](https://lunrjs.com), while lacking other features that MiniSearch has, and being generally more complex to use, might be a better fit for this specific case, as you can specify searches like `"*mon*"`. Take into consideration, though, that those kind of searches will not be performant on big indexes.
