### ISSUE TITLE
Defining documents by array indexes instead of object keys?

### ISSUE THREAD

**Issue by onassar** [lucaong/minisearch#69]
Hi there: is it possible to define objects (and search through them) by array indexes instead of object keys? For example, instead of defining:

    {
        "id": "song-123",
        "title": "Time to Shine"
    }

Defining something like:

    ["song-123", "Time to Shine"]

**Comment by lucaong** [comment]
Hi @onassar 
each document must have an ID. Implicitly using array indexes is not supported, because one can call `addAll` multiple times with different arrays (also see this similar question: https://github.com/lucaong/minisearch/issues/62).

That said, if in your case you have a single array of strings that you want to index, you can assign the IDs yourself:

```javascript
const titles = ["song-123", "Time to Shine", /* ...and more */]
const documents = titles.map((title, i) => { id: i, title: title })
const miniSearch = new MiniSearch({ fields: ['title'] })

miniSearch.addAll(documents)
```

I hope this helps :)

**Comment by onassar** [comment]
Thanks I'll do that :)
