### ISSUE TITLE
example feedback

### ISSUE THREAD

**Issue by joyously** [lucaong/minisearch#72]
I was excited to find minisearch since it has no dependencies, and reading the code of the example. 
But the example is actually a demo, not an example, and it uses React! 
You can't really see how to use autosuggest or the filter etc. if the code is minimized, and there is no link to the repository.
The demo is pretty nice, but it's named "example", not "demo". I was expecting to see some code so I can follow along to do my own. I went to the docs, but that didn't help at all.
Also, why are there two sets of CSS for the demo?
Also, why is the body background color not set (I see my browser default color)?
Also, your repository folder is called "examples" (plural), yet there is only one.

**Comment by lucaong** [comment]
Hi @joyously ,
I am sorry that the example is not what you expected. My goal was to show what can be done with MiniSearch, making use of most of the features. There are dedicated example snippets of code both in the README and in the documentation that show how to use specific features. That said, I am doing my best with the documentation, but I am happy to see contributions to improve it. After all, MiniSearch is open source.

> But the example is actually a demo, not an example, and it uses React!

It is an example application showcasing MiniSearch. If you prefer, you can call it a demo. I honestly don’t think it matters too much. MiniSearch does not come with a UI, so for the example I used React to build the UI. The documentation, on the other hand, does not make use of any external framework or library.

> You can't really see how to use autosuggest or the filter etc. if the code is minimized, and there is no link to the repository.

This very repository you are opening an issue on contains the non-minimized code of the example. It uses the autosuggest feature and the filters, but if you are specifically interested in them, it’s probably better to refer to the relevant sections in the documentation.

> The demo is pretty nice, but it's named "example", not "demo". I was expecting to see some code so I can follow along to do my own. I went to the docs, but that didn't help at all.

Sorry it did not help you. What do you think is missing or confusing in the docs? What could be improved?

> Also, why are there two sets of CSS for the demo?

The example has a single inline CSS stylesheet in the `index.html` page. The other CSS file included by that same page is the typeface from Google Fonts.

> Also, why is the body background color not set (I see my browser default color)?

I can set the background to white. Honestly I didn’t expect users to customize the browser background color, but ok, it’s a fair improvement.

> Also, your repository folder is called "examples" (plural), yet there is only one.

Well, yeah, it’s a single example for now, sorry if that bothers you, but I would not exclude the possibility to add more examples (demos?) in the future.

**Comment by joyously** [comment]
> This very repository you are opening an issue on contains the non-minimized code of the example.

As I said, there is no link to the repository from the example, so all you have is minified code. I had to figure out where the repo was and find the example. (I came from your blog post.)

>  so for the example I used React to build the UI.

Using React makes it difficult to follow the example (especially before I found the repository).

> What do you think is missing or confusing in the docs? What could be improved?

I think what is confusing is that it is Typescript and I don't know how to read that. It seems to be just the bare minimum, like generated docs, without any how or why type of information. I didn't look at it very deeply, because of the weird syntax, and the readme had more useful info. But the readme is not real code, although it's closer.

> The example has a single inline CSS stylesheet in the index.html page.

Sorry, when I saved the page from my browser (before I had found the repository), I saw inline CSS and a CSS file. I see now that was the font CSS.

> Honestly I didn’t expect users to customize the browser background color

There are a lot of sites that forget that detail, but I do a lot of CSS and try to promote always specifying the foreground and background color together, because you never know how your user sets up the browser.

> I would not exclude the possibility to add more examples (demos?) in the future.

If you do, I suggest a single feature at a time, showing the code, or at least linking to the doc or the src file.

**Comment by lucaong** [comment]
Thanks for your response @joyously 

> As I said, there is no link to the repository from the example

Fair point, I will soon add a link to the repo

> Using React makes it difficult to follow the example

I agree, but building a complex example in plain JS might be even more confusing due to the boilerplate code. It could be worth adding a basic example in plain JS though. I'll try to work on it, even though my time is limited (unfortunately MiniSearch is not my paid job, nor a source of income): contributions are more than welcome.

> I think what is confusing is that it is Typescript and I don't know how to read that. It seems to be just the bare minimum, like generated docs, without any how or why type of information. I didn't look at it very deeply, because of the weird syntax, and the readme had more useful info. But the readme is not real code, although it's closer.

I definitely agree that a "How To" section would help. It's in my plans, although again, time is a scarce resource. The code in the README and in the docs _is_ real code though. There is no UI code simply because MiniSearch does not provide a UI: that's up to the developer.

As for TypeScript vs JavaScript, that should not really matter: using TypeScript simply safeguards my code from some kind of mistakes, and makes it easier to generate documentation that contains correct type informations, which is good also when using MiniSearch in plain JS, in order to understand what the interface of a given function is (what kind of arguments, are they optional, what's the return value, etc.). The same information used to be documented with JSDoc before, but there was always the chance of updating the code and forgetting to update the docs: with TypeScript that is not possible. In any case, the documentation is generated with TypeDocs, but it _does not_ assume usage of TypeScript, and only uses plain JS for the code examples.

> There are a lot of sites that forget that detail, but I do a lot of CSS and try to promote always specifying the foreground and background color together, because you never know how your user sets up the browser.

I added now an explicit `background-color` to the CSS. Thanks for the tip.

> If you do, I suggest a single feature at a time, showing the code, or at least linking to the doc or the src file.

That makes sense.
