### ISSUE TITLE
Add options to replace documents / prefilter data

### ISSUE THREAD

**Issue by florianmatz** [lucaong/minisearch#86]
Hi Luca,

really enjoying your work. 

I have one little suggestion, that could be a good improvement.

Let's say we have a component, which receives data as a prop, which is filtered by minisearch.

So, when the data changes (through update etc.) the indexed data stays the same and you manually have to update the index.

Therefore you have to call removeAll(); addAll(newStuff); 
A method like replaceAll(); or a option to addAll(newStuff, killOldStuff = true) would be nice.

Furhtermore a possibility to prefilter data - say by categories would be nice. Of course, there is the "filter"  in the search options, but the compare function is then applied on every search. Wouldn't it be more performant to prefilter by category and then let minisearch to it's magic? Or is this a thing every developer should handle on it's own in your opinion?

I've created a quick demo to illustrate, what I mean:

https://react-hsdd4x.stackblitz.io

Thanks your your lib :)

**Comment by lucaong** [comment]
Hi @florianmatz , thanks for the kind words!

Your suggestions make perfect sense, but I personally think that MiniSearch should provide the "building blocks" for developers to build their app, so I think these features belong to a higher level library. One example of such "higher level" library is the React binding [react-minisearch](https://github.com/lucaong/react-minisearch) (which admittedly could use some help to improve documentation 🙂).

That said, I will think about it a bit: maybe a method like `replaceAll` could be useful after all.

Regarding your second suggestion, I am not sure that I understand correctly, but at the moment the demo you shared is not loading for me. It might be a problem on my side, I will try again later.

Thanks a lot for the interest in MiniSearch!

**Comment by florianmatz** [comment]
Thanks for your fast reply :)

I'm already using react-minisearch as a matter of fact :) - which is a nice addition to MiniSearch.

The demo is only working in Chrome, because Stackblitz seem to have a problem with Webkit -_- 
You can jump to the file directly using this link: https://stackblitz.com/edit/react-hsdd4x?file=src%2FApp.js

Let me try to explain my second question again:

Say, your data has some categories / tags etc.

With mini-search, each and every entry (? or maybe i'm wrong) is compared with the provided filter from the search options, right?

Wouldn't it be faster, to do the filtering BEFORE you have to check each and every entry, because it reducing the amount of compare operations? I mean, you search after a query and then throw 80% away, because it does not match the filter?

What I do in the demo is removing the data from minisearch and replacing it with prefiltered data (by tags, category etc.)
That is actually, where my replaceAll idea came from...

I'm now wondering, what is faster:

- prefiltering, removing data from minisearch, adding and indexing data again
- or, just using the filter option you are providing, because all the prefiltering and re-indexing takes more time than actually "throwing away" some of the results...

Cheers mate!

BTW: I've implemented the demo before mini search with fuse.js - and i have to say, it did not perform as well as your library. Quite cool, if you just compare the weekly downloads on npm :D

**Comment by lucaong** [comment]
Hi @florianmatz , thanks for the explanation, much clearer now!

MiniSearch applies the filter on all results that match the search. That said, on most use cases that's more performant than re-indexing the whole collection.

The only case when re-indexing could be more performant is if there are many small categories, and the search you are performing would return a large number of results in many different categories, so that the number of results _before_ filtering is much larger than the number of documents in the selected category. In this case, it might be more performant to re-index on the fly only the selected category, but I suspect that in practice this would be a rather extreme case, and the actual difference in performance might still be small.

You can think about it this way: indexing is very fast, so much that you are right that it is often practical to reindex everything on the fly, but still takes a time that is proportional to the number of documents and to the "length" of each indexed field in each document. Filtering takes time proportional to the number of results matching the search, and the filtering is normally a simple comparison. Therefore, in order for re-indexing to be worth, the number of results before filtering would have to be larger than the total number of documents in the selected category (much larger if one considers that a simple comparison used for filtering is usually much faster than tokenizing/transforming/indexing each term).

In most production usages that I experienced, even dealing with categorized collections of several tens of thousands of small documents, I always found it worth to filter rather than reindex the category. That said, it's not a mistake to do as you proposed, and might be a good strategy for some cases (including when the total collection is so big that it's necessary to keep only a single category in memory).

I hope this makes it clearer :)

Thanks again for the nice words, I put a lot of effort in making MiniSearch algorithms fast but also as simple as possible, so it is great to hear that this work is appreciated.

**Comment by florianmatz** [comment]
Once again - thank you for for answer and the clarification! So I can go on implementing MiniSearch into our project :). Maybe I'll come back to you with another question ^^

**Comment by lucaong** [comment]
Sure, happy to help!
